<a href="https://colab.research.google.com/github/Mohammad-Mujtaba-Zaidi/T20-Strategy-Predictor/blob/main/T20_Strategy_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Load the datasets
matches = pd.read_csv('/content/drive/MyDrive/T20_Predictor_Project/matches.csv')
deliveries = pd.read_csv('/content/drive/MyDrive/T20_Predictor_Project/deliveries.csv')

# Merge both tables
total_data = deliveries.merge(matches, on='match_id')

# Clean the data
total_data.dropna(subset=['winner'], inplace=True)
total_data['dismissed_player'] = total_data['dismissed_player'].fillna('0')
total_data['dismissal_type'] = total_data['dismissal_type'].fillna('0')
total_data['fielder'] = total_data['fielder'].fillna('0')
total_data['extra_type'] = total_data['extra_type'].fillna('0')

print("All previous steps completed successfully!")
print("Shape of total_data ready for Feature Engineering:", total_data.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
All previous steps completed successfully!
Shape of total_data ready for Feature Engineering: (133379, 42)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

# Read CSV files from drive
matches = pd.read_csv('/content/drive/MyDrive/T20_Predictor_Project/matches.csv')
deliveries = pd.read_csv('/content/drive/MyDrive/T20_Predictor_Project/deliveries.csv')

# Checking data is loaded or not
print("Matches Data Preview:")
display(matches.head(3))

print("\nDeliveries Data Preview:")
display(deliveries.head(3))

Matches Data Preview:

,match_id,season,match_number,stage,date,venue,city,team1,team2,toss_winner,...,second_innings_wickets,second_innings_overs,result,winner,win_by,win_margin,player_of_match,umpire1,umpire2,is_day_night
0,M0001,2008,1,League,2008-03-13,Punjab Cricket Association Stadium,Mohali,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False
1,M0002,2008,2,League,2008-03-14,Greenfield Intl Stadium,Thiruvananthapuram,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,...,3,18.6,normal,Kolkata Knight Riders,wickets,7,Shai Amla,Michael Gough,Simon Taufel,True
2,M0003,2008,3,League,2008-03-15,M. A. Chidambaram Stadium,Chennai,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,...,2,19.0,normal,Chennai Super Kings,runs,81,Lungi Warner,KN Ananthapadmanabhan,Michael Gough,True

Deliveries Data Preview:

,delivery_id,match_id,innings,over,ball,batting_team,bowling_team,striker,non_striker,bowler,batsman_runs,extra_runs,total_runs,extra_type,is_wicket,dismissal_type,dismissed_player,fielder
0,D0000001,M0001,1,1,1,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,2,0,2,NaN,False,NaN,NaN,NaN
1,D0000002,M0001,1,1,2,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,4,0,4,NaN,False,NaN,NaN,NaN
2,D0000003,M0001,1,1,3,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,0,0,0,NaN,True,caught,Yuzvendra Kumar,Aiden Anderson

In [ ]:
# SQL Logic
total_data = deliveries.merge(matches, left_on='match_id', right_on='match_id')

print("Data merge successfully!")
print("Shape of the new merged dataset (Rows, Columns):", total_data.shape)
display(total_data.head(3))

Data merge successfully!
Shape of the new merged dataset (Rows, Columns): (134190, 42)

,delivery_id,match_id,innings,over,ball,batting_team,bowling_team,striker,non_striker,bowler,...,second_innings_wickets,second_innings_overs,result,winner,win_by,win_margin,player_of_match,umpire1,umpire2,is_day_night
0,D0000001,M0001,1,1,1,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False
1,D0000002,M0001,1,1,2,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False
2,D0000003,M0001,1,1,3,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False

In [ ]:
# Checking for missing (null) values in our dataset
print("Missing values in each column:")
print(total_data.isnull().sum())

Missing values in each column:
delivery_id                    0
match_id                       0
innings                        0
over                           0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
batsman_runs                   0
extra_runs                     0
total_runs                     0
extra_type                123441
is_wicket                      0
dismissal_type            126816
dismissed_player          126816
fielder                   129938
season                         0
match_number                   0
stage                          0
date                           0
venue                          0
city                           0
team1                          0
team2                          0
toss_winner                    0
toss_decision                  0
first_innings_score            0
first_innings_wickets          0
first_innings_overs            0
second_innings_score           0
second_innings_wickets         0
second_innings_overs           0
result                         0
winner                       811
win_by                       811
win_margin                     0
player_of_match                0
umpire1                        0
umpire2                        0
is_day_night                   0
dtype: int64

In [ ]:
# Dropping rows where the match has no winner(No Result Matches)
total_data.dropna(subset=['winner'], inplace=True)

# Filling missing values in wicket-related columns with '0'
total_data['dismissed_player'] = total_data['dismissed_player'].fillna('0')
total_data['dismissal_type'] = total_data['dismissal_type'].fillna('0')
total_data['fielder'] = total_data['fielder'].fillna('0')
total_data['extra_type'] = total_data['extra_type'].fillna('0')

print("Data cleaned successfully!")
print("Checking if any missing values are left in 'winner':", total_data['winner'].isnull().sum())
print("New data shape after cleaning:", total_data.shape)

Data cleaned successfully!
Checking if any missing values are left in 'winner': 0
New data shape after cleaning: (133379, 42)

In [ ]:
# Checking for missing (null) values in our dataset
print("Missing values in each column:")
print(total_data.isnull().sum())

Missing values in each column:
delivery_id               0
match_id                  0
innings                   0
over                      0
ball                      0
batting_team              0
bowling_team              0
striker                   0
non_striker               0
bowler                    0
batsman_runs              0
extra_runs                0
total_runs                0
extra_type                0
is_wicket                 0
dismissal_type            0
dismissed_player          0
fielder                   0
season                    0
match_number              0
stage                     0
date                      0
venue                     0
city                      0
team1                     0
team2                     0
toss_winner               0
toss_decision             0
first_innings_score       0
first_innings_wickets     0
first_innings_overs       0
second_innings_score      0
second_innings_wickets    0
second_innings_overs      0
result                    0
winner                    0
win_by                    0
win_margin                0
player_of_match           0
umpire1                   0
umpire2                   0
is_day_night              0
dtype: int64

In [ ]:
# Filter data to get only the 1st innings
first_innings = total_data[total_data['innings'] == 1]

# Calculate total runs scored in the 1st innings for each match
total_scores = first_innings.groupby('match_id')['total_runs'].sum().reset_index()

# Add 1 to get the target score for the chasing team
total_scores['target'] = total_scores['total_runs'] + 1

# Merge this target score back with our main dataset
total_data = total_data.merge(total_scores[['match_id', 'target']], on='match_id')

# Keep only the 2nd innings data (since our model predicts the chase)
chasing_data = total_data[total_data['innings'] == 2]

print("Target scores calculated successfully!")
print("Shape of our new Chasing Data:", chasing_data.shape)
display(chasing_data.head(3))

Target scores calculated successfully!
Shape of our new Chasing Data: (62049, 43)

,delivery_id,match_id,innings,over,ball,batting_team,bowling_team,striker,non_striker,bowler,...,second_innings_overs,result,winner,win_by,win_margin,player_of_match,umpire1,umpire2,is_day_night,target
87,D0000088,M0001,2,1,1,Royal Challengers Bangalore,Kings XI Punjab,Devdutt Agarwal,AB Ashraf,Ambati van der Dussen,...,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False,200
88,D0000089,M0001,2,1,2,Royal Challengers Bangalore,Kings XI Punjab,Devdutt Agarwal,AB Ashraf,Ambati van der Dussen,...,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False,200
89,D0000090,M0001,2,1,3,Royal Challengers Bangalore,Kings XI Punjab,Devdutt Agarwal,AB Ashraf,Ambati van der Dussen,...,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False,200

In [ ]:
# Creating a copy of the data to avoid Pandas warnings
chasing_data = chasing_data.copy()

# Calculating the 'current_score' by taking the cumulative sum of runs per ball
chasing_data['current_score'] = chasing_data.groupby('match_id')['total_runs'].cumsum()

# Calculating 'runs_left' by subtracting the current score from the target
chasing_data['runs_left'] = chasing_data['target'] - chasing_data['current_score']

# Displaying important columns to verify the new calculations
print("Current Score and Runs Left calculated successfully!")
display(chasing_data[['match_id', 'target', 'total_runs', 'current_score', 'runs_left']].head(5))

Current Score and Runs Left calculated successfully!

   match_id  target  total_runs  current_score  runs_left
87    M0001     200           4              4        196
88    M0001     200           1              5        195
89    M0001     200           3              8        192
90    M0001     200           4             12        188
91    M0001     200           2             14        186

In [ ]:
# Calculating 'balls_left'
# In this dataset, 'over' starts at 1. So total balls bowled = (over - 1) * 6 + ball
balls_bowled = (chasing_data['over'] - 1) * 6 + chasing_data['ball']
chasing_data['balls_left'] = 120 - balls_bowled

# Ensuring 'balls_left' doesn't go below 0 (which can happen due to extra balls in the 20th over)
chasing_data['balls_left'] = chasing_data['balls_left'].apply(lambda x: 0 if x < 0 else x)

# Calculating 'wickets_left'
# Taking the cumulative sum of the 'is_wicket' column to count fallen wickets
wickets_fallen = chasing_data.groupby('match_id')['is_wicket'].cumsum()
chasing_data['wickets_left'] = 10 - wickets_fallen

# Displaying the final critical columns
print("Balls Left ans Wickets Left calculated successfully!")
display(chasing_data[['match_id', 'runs_left', 'balls_left', 'wickets_left']].head(5))

Balls Left ans Wickets Left calculated successfully!

   match_id  runs_left  balls_left  wickets_left
87    M0001        196         119            10
88    M0001        195         118            10
89    M0001        192         117            10
90    M0001        188         116            10
91    M0001        186         115            10

In [ ]:
# Calculating Current Run Rate (CRR)
# Formula: (Current Score / Balls Bowled) * 6
# Balls bowled can be found by subtracting balls_left from total 120 balls
balls_bowled = 120 - chasing_data['balls_left']
chasing_data['crr'] = (chasing_data['current_score'] * 6) / balls_bowled

# Calculating Required Run Rate (RRR)
# Formula: (Runs Left / Balls Left) * 6
chasing_data['rrr'] = (chasing_data['runs_left'] * 6) / chasing_data['balls_left']

# Displaying the Run Rated to verify
print("CRR and RRR calculated successfully!")
display(chasing_data[['match_id', 'current_score', 'runs_left', 'crr', 'rrr']].head(5))

CRR and RRR calculated successfully!

   match_id  current_score  runs_left   crr       rrr
87    M0001              4        196  24.0  9.882353
88    M0001              5        195  15.0  9.915254
89    M0001              8        192  16.0  9.846154
90    M0001             12        188  18.0  9.724138
91    M0001             14        186  16.8  9.704348

In [ ]:
# Creating the target variable 'result' (1 if the batting team wins, 0 if they lose)
def check_result(row):
  return 1 if row['batting_team'] == row['winner'] else 0

chasing_data['result'] = chasing_data.apply(check_result, axis=1)

# Selecting only the features required for our Machine Learning model
final_columns = ['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left', 'wickets_left', 'target', 'crr', 'rrr', 'result']
final_data = chasing_data[final_columns]

# Final safety check: dropping any remaining nulls (e.g., missing cities)
# and removing rows where balls_left == 0 to avoid infinite RRR issues
final_data = final_data.dropna()
final_data = final_data[final_data['balls_left'] != 0]

# Shuffling the data so the ML model doesn't learn patterns based on match sequence
final_data = final_data.sample(frac=1)

print("Final dataset ready for Machine Learning!")
print("Final Shape:", final_data.shape)
display(final_data.head(5))

Final dataset ready for Machine Learning!
Final Shape: (62049, 10)

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target,crr,rrr,result
57742,Kolkata Knight Riders,Kings XI Punjab,Bangalore,194,108,9,220,13.0000,10.777778,1
25876,Delhi Daredevils,Mumbai Indians,Mumbai,113,108,9,131,9.0000,6.277778,0
75606,Kolkata Knight Riders,Mumbai Indians,Cuttack,44,95,9,112,16.3200,2.778947,1
16061,Mumbai Indians,Rajasthan Royals,Mumbai,-8,96,10,49,14.2500,-0.500000,0
76757,Chennai Super Kings,Delhi Daredevils,Delhi,75,56,9,217,13.3125,8.035714,0

# Splitting data into train and test

In [ ]:
# Separating features (X) and target (y)
X = final_data.drop('result', axis = 1)
y = final_data['result']

# Importing the splitting function from scikit-learn
from sklearn.model_selection import train_test_split

# Splitting the data: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print("Data successfully split into X (inputs) and y (output)!")
print("Training Data (X_train) Shape:", X_train.shape)
print("Testing Data (X_test) Shape:", X_test.shape)

Data successfully split into X (inputs) and y (output)!
Training Data (X_train) Shape: (49639, 9)
Testing Data (X_test) Shape: (12410, 9)

# One-Hot Encoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Preparing the One-Hot Encoder for the text columns
# drop='first' is used to avoid the dummy variable trap in Machine Learning
step1_encoder = ColumnTransformer([
    ('encoder', OneHotEncoder(sparse_output = False, drop = 'first'), ['batting_team', 'bowling_team', 'city'])
], remainder = 'passthrough')

print("One-Hot Encoder setup complete!")

One-Hot Encoder setup complete!

# Pipeline Concept and Logistic Regression algorithm

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
# 'liblinear' is a great solver for datasets of this size
model = LogisticRegression(solver = 'liblinear')

# Create a Pipeline that chains encoder and the model together
pipe = Pipeline([
    ('step1', step1_encoder),
    ('step2', model)
])

#Train the model using Training Data (X_train and y_train)
pipe.fit(X_train, y_train)

print("Model Training Complete! The AI has learned the T20 winning patterns.")

Model Training Complete! The AI has learned the T20 winning patterns.

# Model Evaluation
using 20% testing data

### Experiment 1: Basic Logistic Regression (Accuracy: 58.99%)
**Observation:** Tested a linear model without feature scaling. It failed to capture the complex, unpredictable nature of T20 cricket, resulting in coin-toss level predictions.

In [ ]:
from sklearn.metrics import accuracy_score

# Ask the trained model to predict results for the unseen testing data
y_pred = pipe.predict(X_test)

# Compare the model's predictions with the actual true results
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy as a percentage
print("Model Evaluation Complete!")
print(f"Accuracy of our T20 Win Predictor: {accuracy * 100:.2f}%")

Model Evaluation Complete!
Accuracy of our T20 Win Predictor: 58.99%

# Random Forest
Due to low accuracy we use Random forest to boost up accuracy

### Experiment 2: Unrestricted Random Forest (Accuracy: 99.72%)
**Observation:** The model showed severe overfitting. In sports prediction, 99% accuracy indicates the model memorized the training data instead of learning real-world cricket logic. Unfit for live user inputs.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize a powerful Random Forest Model
# n_estimators = 100 means we are using 100 decision trees to vote on the outcome
rf_model = RandomForestClassifier(n_estimators = 100, random_state = 42)

# Update our Pipeline with the new model
pipe = Pipeline([
    ('step!', step1_encoder),
    ('step2', rf_model)
])

# Train the model again with X_train and y_train
print("Training Random Forest model.")
pipe.fit(X_train, y_train)

# Predict and check the new accuracy
y_pred = pipe.predict(X_test)
new_accuracy = accuracy_score(y_test, y_pred)

print("Model Upgrade Complete!")
print(f"New Random Forest Accuracy: {new_accuracy * 100:.2f}%")

Training Random Forest model.
Model Upgrade Complete!
New Random Forest Accuracy: 99.72%

# StandardScaler
due to high accuracy in Random Forest which is called Overfitting data , we use StandardScaler for accuracy

### Experiment 3: Logistic Regression with StandardScaler (Accuracy: 59.02%)
**Observation:** Upgraded the linear model by scaling numerical features. The accuracy barely improved, proving definitively that linear models cannot handle the complexity of T20 run-chases.

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Building the professional pipeline with a Scaler added
# step1_encoder will convert text to numbers
# StandardScaler will balance the heavy numbers (like target, runs_left)
# LogisticRegression will calculate the exact win probabilities
pipe = Pipeline([
    ('step1', step1_encoder),
    ('step2', StandardScaler()),
    ('step3', LogisticRegression(solver = 'liblinear'))
])

# Train the upgraded model
pipe.fit(X_train, y_train)

# Predict and check the TRUE realistic accuracy
y_pred = pipe.predict(X_test)
true_accuracy = accuracy_score(y_test, y_pred)

print("Professional Model Training Complete!")
print(f"True Real-World Accuracy: {true_accuracy * 100:.2f}%")

Professional Model Training Complete!
True Real-World Accuracy: 59.02%

# Final Production-Ready Model:
## Tuned Random Forest (max_depth=15)

**Observation:** Applied depth restrictions to stop overfitting. This optimized model balances accuracy with real-world logic, generating realistic win probabilities for unseen matches.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Pipeline with Random Forest
# max_depth=15 prevents the model from overfitting to 99%
pipe = Pipeline([
    ('step1', step1_encoder),
    ('step2', RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42))
])

# Train the model
pipe.fit(X_train, y_train)

# Predict and check Accuracy
y_pred = pipe.predict(X_test)
final_accuracy = accuracy_score(y_test, y_pred)

print("Model Training Successful!")
print(f"Final Random Forest Accuracy: {final_accuracy * 100:.2f}%")

# TESTING PROBABILITY: Let's test the probability for the very first match in our test data
prob = pipe.predict_proba(X_test)[0]
print(f"\nProbability Test for a sample match:")
print(f"Chasing Team Win Chance: {prob[1]*100:.1f}%")
print(f"Defending Team Win Chance: {prob[0]*100:.1f}%")

Model Training Successful!
Final Random Forest Accuracy: 95.08%

Probability Test for a sample match:
Chasing Team Win Chance: 63.0%
Defending Team Win Chance: 37.0%

In [ ]:
import pickle

# Saving our trained pipeline into a file named 'pipe.pkl'
pickle.dump(pipe, open('pipe.pkl', 'wb'))

print("Congratulations! Model successfully saved as 'pipe.pkl'.")

Congratulations! Model successfully saved as 'pipe.pkl'.

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
import pickle

# 1. New sharp model without max_depth limit for realistic probabilities
final_rf = RandomForestClassifier(n_estimators=200, min_samples_leaf=2, random_state=42)

# 2. Building the pipeline with the encoder and the new model
pipe = Pipeline([
    ('step1', step1_encoder),
    ('step2', final_rf)
])

# 3. Training the model (Data X_train and y_train are already in memory)
pipe.fit(X_train, y_train)

# 4. Saving the highly optimized model
pickle.dump(pipe, open('pipe.pkl', 'wb'))
print("Success! The sharp, faculty-ready model has been saved as 'pipe.pkl'.")

Success! The sharp, faculty-ready model has been saved as 'pipe.pkl'.