<a href="https://colab.research.google.com/github/Mohammad-Mujtaba-Zaidi/T20-Strategy-Predictor/blob/main/T20_Strategy_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

# Read CSV files from drive
matches = pd.read_csv('/content/drive/MyDrive/T20_Predictor_Project/matches.csv')
deliveries = pd.read_csv('/content/drive/MyDrive/T20_Predictor_Project/deliveries.csv')

# Checking data is loaded or not
print("Matches Data Preview:")
display(matches.head(3))

print("\nDeliveries Data Preview:")
display(deliveries.head(3))

Matches Data Preview:

,match_id,season,match_number,stage,date,venue,city,team1,team2,toss_winner,...,second_innings_wickets,second_innings_overs,result,winner,win_by,win_margin,player_of_match,umpire1,umpire2,is_day_night
0,M0001,2008,1,League,2008-03-13,Punjab Cricket Association Stadium,Mohali,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False
1,M0002,2008,2,League,2008-03-14,Greenfield Intl Stadium,Thiruvananthapuram,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,...,3,18.6,normal,Kolkata Knight Riders,wickets,7,Shai Amla,Michael Gough,Simon Taufel,True
2,M0003,2008,3,League,2008-03-15,M. A. Chidambaram Stadium,Chennai,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,...,2,19.0,normal,Chennai Super Kings,runs,81,Lungi Warner,KN Ananthapadmanabhan,Michael Gough,True

Deliveries Data Preview:

,delivery_id,match_id,innings,over,ball,batting_team,bowling_team,striker,non_striker,bowler,batsman_runs,extra_runs,total_runs,extra_type,is_wicket,dismissal_type,dismissed_player,fielder
0,D0000001,M0001,1,1,1,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,2,0,2,NaN,False,NaN,NaN,NaN
1,D0000002,M0001,1,1,2,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,4,0,4,NaN,False,NaN,NaN,NaN
2,D0000003,M0001,1,1,3,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,0,0,0,NaN,True,caught,Yuzvendra Kumar,Aiden Anderson

In [4]:
# SQL Logic
total_data = deliveries.merge(matches, left_on='match_id', right_on='match_id')

print("Data merge successfully!")
print("Shape of the new merged dataset (Rows, Columns):", total_data.shape)
display(total_data.head(3))

Data merge successfully!
Shape of the new merged dataset (Rows, Columns): (134190, 42)

,delivery_id,match_id,innings,over,ball,batting_team,bowling_team,striker,non_striker,bowler,...,second_innings_wickets,second_innings_overs,result,winner,win_by,win_margin,player_of_match,umpire1,umpire2,is_day_night
0,D0000001,M0001,1,1,1,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False
1,D0000002,M0001,1,1,2,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False
2,D0000003,M0001,1,1,3,Kings XI Punjab,Royal Challengers Bangalore,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,...,8,15.4,normal,Kings XI Punjab,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False

In [5]:
# Checking for missing (null) values in our dataset
print("Missing values in each column:")
print(total_data.isnull().sum())

Missing values in each column:
delivery_id                    0
match_id                       0
innings                        0
over                           0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
batsman_runs                   0
extra_runs                     0
total_runs                     0
extra_type                123441
is_wicket                      0
dismissal_type            126816
dismissed_player          126816
fielder                   129938
season                         0
match_number                   0
stage                          0
date                           0
venue                          0
city                           0
team1                          0
team2                          0
toss_winner                    0
toss_decision                  0
first_innings_score            0
first_innings_wickets          0
first_innings_overs            0
second_innings_score           0
second_innings_wickets         0
second_innings_overs           0
result                         0
winner                       811
win_by                       811
win_margin                     0
player_of_match                0
umpire1                        0
umpire2                        0
is_day_night                   0
dtype: int64

In [7]:
# Dropping rows where the match has no winner(No Result Matches)
total_data.dropna(subset=['winner'], inplace=True)

# Filling missing values in wicket-related columns with '0'
total_data['dismissed_player'] = total_data['dismissed_player'].fillna('0')
total_data['dismissal_type'] = total_data['dismissal_type'].fillna('0')
total_data['fielder'] = total_data['fielder'].fillna('0')
total_data['extra_type'] = total_data['extra_type'].fillna('0')

print("Data cleaned successfully!")
print("Checking if any missing values are left in 'winner':", total_data['winner'].isnull().sum())
print("New data shape after cleaning:", total_data.shape)

Data cleaned successfully!
Checking if any missing values are left in 'winner': 0
New data shape after cleaning: (133379, 42)

In [8]:
# Checking for missing (null) values in our dataset
print("Missing values in each column:")
print(total_data.isnull().sum())

Missing values in each column:
delivery_id               0
match_id                  0
innings                   0
over                      0
ball                      0
batting_team              0
bowling_team              0
striker                   0
non_striker               0
bowler                    0
batsman_runs              0
extra_runs                0
total_runs                0
extra_type                0
is_wicket                 0
dismissal_type            0
dismissed_player          0
fielder                   0
season                    0
match_number              0
stage                     0
date                      0
venue                     0
city                      0
team1                     0
team2                     0
toss_winner               0
toss_decision             0
first_innings_score       0
first_innings_wickets     0
first_innings_overs       0
second_innings_score      0
second_innings_wickets    0
second_innings_overs      0
result                    0
winner                    0
win_by                    0
win_margin                0
player_of_match           0
umpire1                   0
umpire2                   0
is_day_night              0
dtype: int64